# Generated by Django 4.2.20 on 2026-06-12 18:57

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('service', models.CharField(choices=[('Logo Digitizing', 'Logo Digitizing'), ('3D Puff Embroidery', '3D Puff Embroidery'), ('Cap Digitizing', 'Cap Digitizing'), ('Screen Printing', 'Screen Printing'), ('Vinyl Cutting / HTV', 'Vinyl Cutting / HTV'), ('Digital Printing & Stickers', 'Digital Printing & Stickers'), ('Corporate Uniforms', 'Corporate Uniforms'), ('Sports Uniforms', 'Sports Uniforms'), ('Custom Design Work', 'Custom Design Work'), ('Other', 'Other')], max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_type', models.CharField(choices=[('digitizing', 'Embroidery Digitizing'), ('patches', 'Patches'), ('vector', 'Vector Art')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('quoted', 'Quoted'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('design_name', models.CharField(max_length=200)),
                ('po_number', models.CharField(blank=True, max_length=100)),
                ('width_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('height_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('size_unit', models.CharField(blank=True, choices=[('in', 'Inches'), ('cm', 'CM'), ('mm', 'MM')], default='in', max_length=5)),
                ('fabric', models.CharField(blank=True, max_length=100)),
                ('colors', models.PositiveIntegerField(blank=True, null=True)),
                ('placement', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('urgent', models.BooleanField(default=False)),
                ('date_needed', models.DateField(blank=True, null=True)),
                ('design_file', models.FileField(blank=True, null=True, upload_to='quotes/designs/')),
                ('patch_type', models.CharField(blank=True, max_length=100)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('border_type', models.CharField(blank=True, max_length=100)),
                ('backing', models.CharField(blank=True, max_length=100)),
                ('thread_color', models.TextField(blank=True)),
                ('embroidery_pct', models.CharField(blank=True, max_length=10)),
                ('vector_format', models.CharField(blank=True, max_length=50)),
                ('background', models.CharField(blank=True, max_length=50)),
                ('quoted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('digitizing', 'Embroidery Digitizing'), ('patches', 'Patches'), ('vector', 'Vector Art')], max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('delivered', 'Delivered')], default='new', max_length=20)),
                ('design_name', models.CharField(max_length=200)),
                ('po_number', models.CharField(blank=True, max_length=100)),
                ('width_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('height_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('size_unit', models.CharField(blank=True, choices=[('in', 'Inches'), ('cm', 'CM'), ('mm', 'MM')], default='in', max_length=5)),
                ('format', models.CharField(blank=True, choices=[('DST', 'DST'), ('PES', 'PES'), ('EXP', 'EXP'), ('JEF', 'JEF'), ('VP3', 'VP3'), ('EMB', 'EMB'), ('XXX', 'XXX'), ('OTHER', 'Other')], max_length=10)),
                ('fabric', models.CharField(blank=True, max_length=100)),
                ('colors', models.PositiveIntegerField(blank=True, null=True)),
                ('placement', models.CharField(blank=True, max_length=100)),
                ('instructions', models.TextField(blank=True)),
                ('urgent', models.BooleanField(default=False)),
                ('date_needed', models.DateField(blank=True, null=True)),
                ('design_file', models.FileField(blank=True, null=True, upload_to='orders/designs/')),
                ('reference_file', models.FileField(blank=True, null=True, upload_to='orders/references/')),
                ('patch_type', models.CharField(blank=True, max_length=100)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('border_type', models.CharField(blank=True, max_length=100)),
                ('backing', models.CharField(blank=True, max_length=100)),
                ('thread_color', models.TextField(blank=True)),
                ('embroidery_pct', models.CharField(blank=True, max_length=10)),
                ('vector_format', models.CharField(blank=True, max_length=50)),
                ('background', models.CharField(blank=True, max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('uninvoiced', 'Uninvoiced'), ('unpaid', 'Unpaid'), ('paid', 'Paid')], default='uninvoiced', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
